import bcrypt from "bcryptjs";

export const dummyTexts = [
  "It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust.",
  "She glanced up into the sky to watch the clouds taking shape. First, she saw a dog. Next, it was an elephant. Finally, she saw a giant umbrella and at that moment the rain began to pour.",
  "She was aware that things could go wrong. In fact, she had trained her entire life in anticipation that things would go wrong one day. She had quiet confidence as she started to see that this was the day that all her training would be worthwhile and useful. At this point, she had no idea just how wrong everything would go that day.",
  "She put the pen to paper but she couldn't bring herself to actually write anything. She just stared at the blank card and wondered what words she could write that would help in even a small way. She thought of a dozen ways to begin but none seemed to do justice to the situation. There were no words that could help and she knew it.",
  "Dragons don't exist they said. They are the stuff of legend and people's imagination. Greg would have agreed with this assessment without a second thought 24 hours ago. But now that there was a dragon staring directly into his eyes, he questioned everything that he had been told.",
  "She didn't like the food. She never did. She made the usual complaints and started the tantrum he knew was coming. But this time was different. Instead of trying to placate her and her unreasonable demands, he just stared at her and watched her meltdown without saying a word.",
  "Then came the night of the first falling star. It was seen early in the morning, rushing over Winchester eastward, a line of flame high in the atmosphere. Hundreds must have seen it and taken it for an ordinary falling star. It seemed that it fell to earth about one hundred miles east of him.",
  "He walked down the steps from the train station in a bit of a hurry knowing the secrets in the briefcase must be secured as quickly as possible. Bounding down the steps, he heard something behind him and quickly turned in a panic. There was nobody there but a pair of old worn-out shoes were placed neatly on the steps he had just come down. Had he past them without seeing them? It didn't seem possible. He was about to turn and be on his way when a deep chill filled his body.",
  "The leather jacked showed the scars of being his favorite for years. It wore those scars with pride, feeling that they enhanced his presence rather than diminishing it. The scars gave it character and had not overwhelmed to the point that it had become ratty. The jacket was in its prime and it knew it.",
  "Was it a whisper or was it the wind? He wasn't quite sure. He thought he heard a voice but at this moment all he could hear was the wind rustling the leaves of the trees all around him. He stopped and listened more intently to see if he could hear the voice again. Nothing but the wind rustling the leaves could be heard. He was about to continue his walk when he felt a hand on his shoulder, and he quickly turned to see who it was. There was nobody there, but he heard the voice again.",
  "A long black shadow slid across the pavement near their feet and the five Venusians, very much startled, looked overhead. They were barely in time to see the huge gray form of the carnivore before it vanished behind a sign atop a nearby building which bore the mystifying information 'Pepsi-Cola.'",
  "'So, what do you think?' he asked nervously. He wanted to know the answer, but at the same time, he didn't. He'd put his heart and soul into the project and he wasn't sure he'd be able to recover if they didn't like what he produced. The silence from the others in the room seemed to last a lifetime even though it had only been a moment since he asked the question. 'So, what do you think?' he asked again.",
  "The words hadn't flowed from his fingers for the past few weeks. He never imagined he'd find himself with writer's block, but here he sat with a blank screen in front of him. That blank screen taunting him day after day had started to play with his mind. He didn't understand why he couldn't even type a single word, just one to begin the process and build from there. And yet, he already knew that the eight hours he was prepared to sit in front of his computer today would end with the screen remaining blank.",
  "The words hadn't flowed from his fingers for the past few weeks. He never imagined he'd find himself with writer's block, but here he sat with a blank screen in front of him. That blank screen taunting him day after day had started to play with his mind. He didn't understand why he couldn't even type a single word, just one to begin the process and build from there. And yet, he already knew that the eight hours he was prepared to sit in front of his computer today would end with the screen remaining blank.",
  "It was a question of which of the two she preferred. On the one hand, the choice seemed simple. The more expensive one with a brand name would be the choice of most. It was the easy choice. The safe choice. But she wasn't sure she actually preferred it.",
  "Twenty-five stars were neatly placed on the piece of paper. There was room for five more stars but they would be difficult ones to earn. It had taken years to earn the first twenty-five, and they were considered the 'easy' ones.",
  "He heard the crack echo in the late afternoon about a mile away. His heart started racing and he bolted into a full sprint. 'It wasn't a gunshot, it wasn't a gunshot,' he repeated under his breathlessness as he continued to sprint.",
  "She was aware that things could go wrong. In fact, she had trained her entire life in anticipation that things would go wrong one day. She had quiet confidence as she started to see that this was the day that all her training would be worthwhile and useful. At this point, she had no idea just how wrong everything would go that day.",
  "Benny was tired. Not the normal every day tired from a hard day o work. The exhausted type of tired where you're surprised your body can even move. All he wanted to do was sit in front of the TV, put his feet up on the coffee table, and drink a beer. The only issue was that he had forgotten where he lived.",
  "The robot clicked disapprovingly, gurgled briefly inside its cubical interior and extruded a pony glass of brownish liquid. 'Sir, you will undoubtedly end up in a drunkard's grave, dead of hepatic cirrhosis,' it informed me virtuously as it returned my ID card. I glared as I pushed the glass across the table.",
];

export const dummyComments = [
  " But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust.",
  "She glanced up into the sky to watch the clouds taking shape.",
  "She was aware that things could go wrong. In fact, she had trained her entire life in anticipation that things would go wrong one day. She had quiet confidence as she started to see that this was the day that all her training would be worthwhile and useful. At this point, she had no idea just how wrong everything would go that day.",
  "She put the pen to paper but she couldn't bring herself to actually write anything.",
  "Dragons don't exist they said. They are the stuff of legend and people's imagination. But now that there was a dragon staring directly into his eyes, he questioned everything that he had been told.",
  "She didn't like the food. But this time was different. Instead of trying to placate her and her unreasonable demands, he just stared at her and watched her meltdown without saying a word.",
  "Then came the night of the first falling star.",
  "He walked down the steps from the train station in a bit of a hurry knowing the secrets in the briefcase must be secured as quickly as possible.",
  "The leather jacked showed the scars of being his favorite for years.",
  "Was it a whisper or was it the wind? He wasn't quite sure.",
  "A long black shadow slid across the pavement near their feet and the five Venusians, very much startled, looked overhead.",
  "'So, what do you think?' he asked nervously.",
  " He never imagined he'd find himself with writer's block, but here he sat with a blank screen in front of him. That blank screen taunting him day after day had started to play with his mind. He didn't understand why he couldn't even type a single word, just one to begin the process and build from there. And yet, he already knew that the eight hours he was prepared to sit in front of his computer today would end with the screen remaining blank.",
  "The words him day after day had started to play with his mind.",
  "It was a question of which of the two she preferred. On the one hand, the choice seemed simple.",
  "Twenty-five stars were neatly placed on the piece of paper. There was room for five more stars but they would be difficult ones to earn.",
  "He heard the crack echo in the late afternoon about a mile away. His heart started racing and he bolted into a full sprint.",
  "She was aware that things could go wrong that things would go wrong one day. She had quiet confidence would be worthwhile and useful..",
  "Benny was tired. Not the normal every day tired from a hard day o work. The only issue was that he had forgotten where he lived.",
  "Sir, you will undoubtedly end up in a drunkard's grave, dead of hepatic cirrhosis,' it informed me virtuously as it returned my ID card. I glared as I pushed the glass across the table.",
];

export const dummyReplies = [
  " But that point was decided fo..",
  "She was aware that things could go wrong. y.",
  "She put the pen to ",
  "Dragons don't exist they said. But now that there was a dragon staring directly into his eyes, he questioned everything that he had been told.",
  "She didn't her meltdown without saying a word.",
  "Then came the night of the first falling star.",
  "He walked down the steps ",
  "A long black shadow slid across the pavement near their ",
  " He never imagined he'd find ere he sat with a blank screen in front of him. That blank screen taunting him day after day had started to play with his mind. He didn't understand why he couldn't even type a single word, just one to begin the process and build from there. And yet, he already knew that the eight hours he was prepared to sit in front of his computer today would end with the screen remaining blank.",
  "The words  to play with his mind.",
  "It was a question of which of the two she preferred.  There was room for five more stars but they would be difficult ones to earn.",
  "He heard the crack echo in the late afternoon about . The only issue was that he had forgotten where he lived.",
  "Sir.",
];

export const dummyReplyReplies = [
  " But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust.",
  "She glanced up into the sky to watch the clouds taking shape.",
  "She  day. She had quiet confidence as she  no idea just how wrong everything would go that day.",
  "She put the pen to ",
  "Drago different. Instead of trying to placate her and her unreasonable demands, he just stared at her and watched her meltdown without saying a word.",
  "Then came ",
  "He walked  the secrets in the briefcase must be ",
  "The leather jacked showed the scars of being his favorite for years.",
  "Was it sure.",
  "A long black shadow slid across the pavement near t",
  "'So, what do you think?' he asked nervously.",
  " He never imagined he' ",
  "It was a On the one hand, the choice seemed simple.",
  "Twenty-five There was room for five more stars but they would be difficult ones to earn.",
  "He heard the crack echo. His heart started racing and he bolted into a full sprint.",
  "She was aware that things..",
  "Benny was tired. Not the normal ",
  "Sir, you will undoubtedly dead of hepatic cirrhosis,' .",
];

export const users = [
  {
    fname: "Meron",
    lname: "Tegegn",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "meri.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/2.jpg",
  },
  {
    fname: "Aster",
    lname: "Molalign",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "astuka.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/3.jpg",
  },
  {
    fname: "Kefa",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "keffamideksa.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/4.jpg",
  },
  {
    fname: "Zemen",
    lname: "Kebede",
    profilepic: "/users/5.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zemenu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Zinash",
    lname: "Amare",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "ziniabiy.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/6.jpg",
  },
  {
    fname: "Zenit",
    lname: "Molla",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "amanii.zii@gmail.com",
    password: bcrypt.hashSync("zenit.Oath.49", 10),
    profilepic: "/users/7.jpg",
  },
  {
    fname: "Zerfe",
    lname: "Moges",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zerfe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/8.jpg",
  },
  {
    fname: "Manaye",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "mana.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/10.jpg",
  },
  {
    fname: "Zetseat",
    lname: "Ferede",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zetsu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/11.jpg",
  },
  {
    fname: "Bereket",
    lname: "Asseffa",
    profilepic: "/users/12.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "beki.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Afomia",
    lname: "Anagaw",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "afomi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/13.jpg",
  },
  {
    fname: "Menberu",
    lname: "Zemi",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "menbe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/14.jpg",
  },
  {
    fname: "Haymi",
    lname: "Alaska",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Tomas",
    lname: "Kerebih",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "meri1.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/2.jpg",
  },
  {
    fname: "Dawit",
    lname: "Molalign",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "astuk2.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/3.jpg",
  },
  {
    fname: "Mazengia",
    lname: "Asgedom",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "keffamideksa3.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/4.jpg",
  },
  {
    fname: "Lij Yared",
    lname: "Kebede",
    profilepic: "/users/5.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zemenu4.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Enatnesh",
    lname: "Kelemu",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "ziniabiy5.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/6.jpg",
  },
  {
    fname: "Zemenay",
    lname: "Molla",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "amanii6.zii@gmail.com",
    password: bcrypt.hashSync("zenit.Oath.49", 10),
    profilepic: "/users/7.jpg",
  },
  {
    fname: "Rebeka",
    lname: "Alene",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zerfe7.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/8.jpg",
  },
  {
    fname: "Zenaw",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "mana8.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/10.jpg",
  },
  {
    fname: "Feleke",
    lname: "Anagaw",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zetsu9.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/11.jpg",
  },
  {
    fname: "Beki",
    lname: "Amare",
    profilepic: "/users/12.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "beki77.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Afewerk",
    lname: "Anagaw",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "afomi99.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/13.jpg",
  },
  {
    fname: "neberu",
    lname: "Shegaw",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "menbe555.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/14.jpg",
  },
  {
    fname: "Asnake",
    lname: "Yekoye",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyami875.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Ermiyas",
    lname: "Tegegn",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "meri66.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/2.jpg",
  },
  {
    fname: "Aster",
    lname: "Kelemu",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "astuka912.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/3.jpg",
  },
  {
    fname: "Yisak",
    lname: "Mengesha",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "keffamideksa98.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/4.jpg",
  },
  {
    fname: "Meles",
    lname: "Tigray",
    profilepic: "/users/5.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zemenu4zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Mekbib",
    lname: "Fetene",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "ziniabiy786.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/6.jpg",
  },
  {
    fname: "Elsabet",
    lname: "Molla",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "amanii33.zii@gmail.com",
    password: bcrypt.hashSync("zenit.Oath.49", 10),
    profilepic: "/users/7.jpg",
  },
  {
    fname: "Dibora",
    lname: "Moges",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zerf33e.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/8.jpg",
  },
  {
    fname: "Aster",
    lname: "Sitotaw",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "maenaee.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/10.jpg",
  },
  {
    fname: "Mastewal",
    lname: "Ferede",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zeeetsu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/11.jpg",
  },
  {
    fname: "Markos",
    lname: "Asseffa",
    profilepic: "/users/12.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "bekiff.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Eyasu",
    lname: "Anagaw",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "afomeei.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/13.jpg",
  },
  {
    fname: "Eskezia",
    lname: "Zemi",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "mendbe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/14.jpg",
  },
  {
    fname: "Asrat",
    lname: "Yekoke",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyddami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Betty",
    lname: "Tegegn",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "merddi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/2.jpg",
  },
  {
    fname: "Bitanya",
    lname: "Molalign",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "astuffka.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/3.jpg",
  },
  {
    fname: "Ephrem",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "keffffamideksa.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/4.jpg",
  },
  {
    fname: "Ashenafi",
    lname: "Zelalem",
    profilepic: "/users/5.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zemffenu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Fikir",
    lname: "Amare",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "ff.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/6.jpg",
  },
  {
    fname: "Mekuriaw",
    lname: "Molla",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "amanffii.zii@gmail.com",
    password: bcrypt.hashSync("zenit.Oath.49", 10),
    profilepic: "/users/7.jpg",
  },
  {
    fname: "Melke",
    lname: "Zemenu",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zerf44e.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/8.jpg",
  },
  {
    fname: "Melkamu",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "44mana.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/10.jpg",
  },
  {
    fname: "Mekuannt",
    lname: "Ferede",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zet33dsu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/11.jpg",
  },
  {
    fname: "Addisu",
    lname: "Asseffa",
    profilepic: "/users/12.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "be321ki.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Alem",
    lname: "Anagaw",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "afomalemi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/13.jpg",
  },
  {
    fname: "Lealem",
    lname: "Zemi",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "menleamlembe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/14.jpg",
  },
  {
    fname: "Biruk",
    lname: "Alaska",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyburrami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Merry",
    lname: "Zelalem",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "me329meri.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/2.jpg",
  },
  {
    fname: "Masti",
    lname: "Molalign",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "asmastituka.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/3.jpg",
  },
  {
    fname: "Dubale",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "keffamiddubeeksa.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/4.jpg",
  },
  {
    fname: "Mazengia",
    lname: "Kebede",
    profilepic: "/users/5.jpg",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zemmazenu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Tadele",
    lname: "Boggale",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zintadabiy.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/6.jpg",
  },
  {
    fname: "Tadila",
    lname: "Molla",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "amandadii.zii@gmail.com",
    password: bcrypt.hashSync("zenit.Oath.49", 10),
    profilepic: "/users/7.jpg",
  },
  {
    fname: "Masresha",
    lname: "Genetu",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zmaserfe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/8.jpg",
  },
  {
    fname: "Alamiraw",
    lname: "Boggale",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "maalamirna.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/10.jpg",
  },
  {
    fname: "Shita",
    lname: "Zemenu",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zetsgsu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/11.jpg",
  },
  {
    fname: "Sewnet",
    lname: "Asseffa",
    profilepic: "/users/12.jpg",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "beksewi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Betty",
    lname: "Wolelaw",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "afbeteyomi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/13.jpg",
  },
  {
    fname: "Neberu",
    lname: "Sewnet",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "menebnbe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/14.jpg",
  },
  {
    fname: "yenew",
    lname: "Yeshisew",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyayeshimi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Yeshi",
    lname: "Tegegn",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "meyeshiri.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/2.jpg",
  },
  {
    fname: "Yeshiwork",
    lname: "Molalign",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "astuyeshika.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/3.jpg",
  },
  {
    fname: "Yikdem",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "keffamyikideksa.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/4.jpg",
  },
  {
    fname: "Remila",
    lname: "Mohammed",
    profilepic: "/users/5.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zemefozireminu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Fatima",
    lname: "Ahmed",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zinifatiabiy.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/6.jpg",
  },
  {
    fname: "Mohammed",
    lname: "Abdu",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "amamohanii.zii@gmail.com",
    password: bcrypt.hashSync("zenit.Oath.49", 10),
    profilepic: "/users/7.jpg",
  },
  {
    fname: "Kedir",
    lname: "Kahlid",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zekeddirrfe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/8.jpg",
  },
  {
    fname: "Feysa",
    lname: "Gelemso",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "mfeyaana.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/10.jpg",
  },
  {
    fname: "Motuuma",
    lname: "Gelet",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zetgeletsu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/11.jpg",
  },
  {
    fname: "Shimiles",
    lname: "Asseffa",
    profilepic: "/users/12.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "bekshii.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Dereje",
    lname: "Anagaw",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "afoderemi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/13.jpg",
  },
  {
    fname: "Mesay",
    lname: "Zemi",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "menmessibe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/14.jpg",
  },
  {
    fname: "Messi",
    lname: "Alaska",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyamessmi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Kalkidan",
    lname: "Masresha",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hykakiami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Seid",
    lname: "Mohammed",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "hyseyami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Sada",
    lname: "Geremew",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyadsadmi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Sadiya",
    lname: "Gutema",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hdaddiyami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Eyerus",
    lname: "Zeleke",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyaeyezemi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Zemzem",
    lname: "Markos",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyamzemi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Zita",
    lname: "Teshale",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zitatata.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Lamrot",
    lname: "Fetene",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "lami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Gedefaw",
    lname: "Kelemu",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "hygedeami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Gedefaye",
    lname: "Ayanaa",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "geddeiaay.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Ayantu",
    lname: "Mengesha",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyamayyai.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Hachhalu",
    lname: "Oromo",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "hyhacchami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Nebiyu",
    lname: "Simon",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "nebibii.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Simon",
    lname: "Gezahegn",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "smionon.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Keneni",
    lname: "Oromia",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "keneni.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Zeleke",
    lname: "Gessesse",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "hyzeami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Zele",
    lname: "Mekuria",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "hyazelemi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Tsebaot",
    lname: "Petros",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hytsetseami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Moses",
    lname: "Girta",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "hymosessami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Amani",
    lname: "Z Man",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "hyamzezei.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Elsi",
    lname: "Habesha",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyaesslimi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Zita",
    lname: "Yihune",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hzezitayami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Mimi",
    lname: "Kefe",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyammimii.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Fikirte",
    lname: "Demesew",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "fekirtteee.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Srawdink",
    lname: "Mame",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "sirawdink444.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
];

export const stories = [
  {
    storyid: 1,
    fname: "Amanuel",
    lname: "Ferede",
    profilepic: "/users/1.jpg",
    post: "/users/15.jpg",
  },
  {
    storyid: 2,
    fname: "Meron",
    lname: "Tegegn",
    profilepic: "/users/2.jpg",

    post: "/users/14.jpg",
  },
  {
    storyid: 3,
    fname: "Aster",
    lname: "Molalign",
    profilepic: "/users/3.jpg",

    post: "/users/13.jpg",
  },
  {
    storyid: 4,
    fname: "Kefa",
    lname: "Abebe",
    profilepic: "/users/4.jpg",

    post: "/users/12.jpg",
  },
  {
    storyid: 5,
    fname: "Zemen",
    lname: "Kebede",
    profilepic: "/users/5.jpg",

    post: "/users/11.jpg",
  },
  {
    storyid: 6,
    fname: "Zinash",
    lname: "Amare",
    profilepic: "/users/6.jpg",

    post: "/users/10.jpg",
  },
  {
    storyid: 7,
    fname: "Zenit",
    lname: "Molla",
    profilepic: "/users/7.jpg",

    post: "/users/9.jpg",
  },
  {
    storyid: 8,
    fname: "Zerfe",
    lname: "Moges",
    profilepic: "/users/8.jpg",

    post: "/users/8.jpg",
  },
  {
    storyid: 10,
    fname: "Mona",
    lname: "Abebe",
    profilepic: "/users/10.jpg",
    post: "/users/7.jpg",
  },
  {
    storyid: 11,
    fname: "Aman",
    lname: "Ferede",
    profilepic: "/users/11.jpg",
    post: "/users/6.jpg",
  },
  {
    storyid: 12,
    fname: "Bezi",
    lname: "Afomia",
    profilepic: "/users/12.jpg",
    post: "/users/5.jpg",
  },
  {
    storyid: 13,
    fname: "Mani",
    lname: "Anagaw",
    profilepic: "/users/13.jpg",
    post: "/users/4.jpg",
  },
  {
    storyid: 14,
    fname: "Moti",
    lname: "Zemi",
    profilepic: "/users/14.jpg",
    post: "/users/3.jpg",
  },
  {
    storyid: 15,
    fname: "Haymi",
    lname: "Alaska",
    profilepic: "/users/15.jpg",
    post: "/users/2.jpg",
  },
];

export const reactionTypes = [
  "like",
  "love",
  "care",
  "haha",
  "wow",
  "sad",
  "angry",
];

export const pages = [
  {
    name: "Ethiopian Artists",
    profilePicture: "/pages/ea.jpg",
  },

  {
    name: "መረጃ mereja",
    profilePicture: "/pages/mereja.jpg",
  },
  {
    name: "Global News",
    profilePicture: "/pages/gn.jpg",
  },

  {
    name: "Beauties of Africa",
    profilePicture: "/pages/ba.jpg",
  },
  {
    name: "Nobody cares",
    profilePicture: "/pages/nb.jpg",
  },
];

export const groups = [
  {
    name: "Ai generators",
    profilePicture: "/groups/ag.jpg",
  },

  {
    name: "Web developers",
    profilePicture: "/groups/wd.jpg",
  },
  {
    name: "Gospel for Ethiopia",
    profilePicture: "/groups/ge.jpg",
  },

  {
    name: "Habesha Mems",
    profilePicture: "/groups/hm.jpg",
  },
  {
    name: "እንመካከር",
    profilePicture: "/groups/enm.jpg",
  },
];
