import type { Metadata } from "next";

import "./globals.css";

import AppProvider from "./store/appprovider";
import NextAuthSessionProvider from "./providers/nextauthprovider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>
          <AppProvider>{children}</AppProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
